
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '1FE5C3B3B1753642CB2594995592918B'
    
_lr_action_items = {'RPAREN':([9,10,14,],[11,-4,-5,]),'DATATYPE':([8,13,],[10,14,]),'CREATE':([0,2,],[-2,3,]),'COMMA':([9,10,14,],[12,-4,-5,]),'LPAREN':([4,7,],[6,-3,]),'TABLE':([3,],[5,]),'ID':([5,6,12,],[7,8,13,]),'$end':([1,11,],[0,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'table':([0,],[1,]),'table_pmb':([2,],[4,]),'columns':([6,],[9,]),'init_mark':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> table","S'",1,None,None,None),
  ('table -> init_mark table_pmb LPAREN columns RPAREN','table',5,'p_create_table','syntax_analyzer.py',18),
  ('init_mark -> <empty>','init_mark',0,'p_init_mark','syntax_analyzer.py',45),
  ('table_pmb -> CREATE TABLE ID','table_pmb',3,'p_table_preamble','syntax_analyzer.py',53),
  ('columns -> ID DATATYPE','columns',2,'p_columns_empty','syntax_analyzer.py',58),
  ('columns -> columns COMMA ID DATATYPE','columns',4,'p_columns_recursive','syntax_analyzer.py',64),
]
